INSERT INTO picture (file_name, content_type, url) VALUES ('aardbei_snack.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/aardbei_snack.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('amandelen_snack.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/amandelen_snack.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('baileys_snack.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/baileys_snack.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('banaan_snack.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/banaan_snack.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('capuccino_snack.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/capuccino_snack.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('citroen_snack.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/citroen_snack.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('cocos_snack.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/cocos_snack.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('creme_catalana_snack.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/creme_catalana_snack.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('bosvruchten_glutenfree.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/bosvruchten_glutenfree.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('hazelnoot_glutenfree.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/hazelnoot_glutenfree.jpg')
INSERT INTO picture (file_name, content_type, url) VALUES ('limoncello_glutenfree.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/limoncello_glutenfree.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('pistache_glutenfree.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/pistache_glutenfree.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('ricotta_glutenfree.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/ricotta_glutenfree.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('tiramisu_glutenfree.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/tiramisu_glutenfree.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('wittechocola_glutenfree.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/wittechocola_glutenfree.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('zoutecaramel_glutenfree.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/zoutecaramel_glutenfree.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('hazelnoot_vegan.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/hazelnoot_vegan.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('limoncello_vegan.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/limoncello_vegan.jpg');
INSERT INTO picture (file_name, content_type, url) VALUES ('pistache_vegan.jpg', 'image/jpeg', 'http://localhost:8080/pictures/download/pistache_vegan.jpg');

